### ISSUE TITLE
How to use this data?

### ISSUE THREAD

**Issue by supercbt** [Hypatiaalegra/LogicGame-Data#2]

**Comment by Hypatiaalegra** [comment]
> The zh_all and en_all files are used as input data for [Our Codabench Submission](https://www.codabench.org/competitions/4140/) where you can utilize the contexts provided in these files as prompts to obtain model responses for evaluation. 

You can download these two files and use the **contexts** field to prompt your model. After obtaining the model's response, store it in the **model_response** field corresponding to each **qid**. Then, submit the generated files (including **qid** and **model_response** ) to our Codabench according to the guidelines, which explain how to zip and format the files in `.jsonl` for both versions. You can check the final results on Codabench in just a few minutes.
