### ISSUE TITLE
Submission status is failed

### ISSUE THREAD

**Issue by qiuxiaoyu9954** [Hypatiaalegra/LogicGame-Data#3]
My submission status is failed. I have ensured that my folder format and file content format meet the requirements, but after submitting the zip file, the scoring log shows the following error:
> Traceback (most recent call last):
>   File "/app/program/score.py", line 112, in <module>
>     main()
>   File "/app/program/score.py", line 57, in main
>     if res_en is not None and (res_en != "NF").any().any():
> AttributeError: 'bool' object has no attribute 'any'

How can I solve this problem?

**Comment by Hypatiaalegra** [comment]
Thanks for raising this problem! It seems that the scoring program has some errors leading to your failure submission. And we're working on fixing it. I will let you know once it's fixed. 
p.s.  I notice something has gone wrong in the codabench platform, so you might expect a longer time on solving this issue, apologize for that.

**Comment by qiuxiaoyu9954** [comment]
Thank you very much for your reply!
